[package]
name = "code-backend-client"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codex-backend-client = { workspace = true }
