name: 🎁 Feature Request
description: Propose a new feature for Code
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Is Code missing a feature that you'd like to see? Feel free to propose it here.

        Before you submit a feature:
        1. Search existing issues for similar features. If you find one, 👍 it rather than opening a new one.
        2. Please be aware that this feature may be automatically implemented through our Issue Triage - if this happens you will receive a reply to this issue with information on how to run it. We'd really appreciate any feedback on the implementation as it helps us improve the feature for everyone!

  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
    validations:
      required: true