[package]
edition = "2024"
name = "code-mcp-types"
version = { workspace = true }

[lib]
name = "mcp_types"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
upstream-mcp-types = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
